<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GitHubActivityReporter.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GitHubActivityReporter.GitHub" />
    <InternalsVisibleTo Include="GitHubActivityReporter.Core.Tests" />
    <InternalsVisibleTo Include="GitHubActivityReporter.GitHub.Tests" />
    <InternalsVisibleTo Include="GitHubActivityReporter.Security.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
