namespace GitHubActivityReporter.Bootstrap.Templates;

/// <summary>Scriban template of the generated GitHub Actions workflow.</summary>
public static class WorkflowTemplate
{
    public const string FileName = "update-activity-report.yml";

    public const string RelativeDirectory = ".github/workflows";

    public const string Scriban =
        """
        # This file is generated by github-activity-reporter.
        # Re-run `github-activity-reporter install-workflow` after changing the schedule.
        name: {{ workflow_name }}

        on:
          workflow_dispatch:
        {{- if cron }}
          schedule:
            # {{ schedule_description }}
            - cron: "{{ cron }}"
        {{- end }}

        permissions:
          contents: write

        concurrency:
          group: activity-report
          cancel-in-progress: false

        jobs:
          update-activity-report:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout profile repository
                uses: actions/checkout@v4
                with:
                  fetch-depth: 0

              - name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                  dotnet-version: "{{ dotnet_version }}"

              - name: Restore
                run: dotnet restore {{ solution_path }}

              - name: Build
                run: dotnet build {{ solution_path }} --configuration Release --no-restore

              - name: Test
                run: dotnet test {{ solution_path }} --configuration Release --no-build

              - name: Generate activity report
                env:
                  {{ token_secret_name }}: ${{ '{{' }} secrets.{{ token_secret_name }} {{ '}}' }}
                run: dotnet run --project {{ cli_project_path }} --configuration Release --no-build -- run --config {{ config_path }}

              - name: Validate generated output
                run: dotnet run --project {{ cli_project_path }} --configuration Release --no-build -- validate --config {{ config_path }}

              - name: Detect changes
                id: changes
                run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changed=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "changed=false" >> "$GITHUB_OUTPUT"
                  fi

              - name: Commit and push
                if: steps.changes.outputs.changed == 'true'
                run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git commit -m "{{ commit_message }}"
                  git push origin HEAD:{{ branch }}
        """;
}
