namespace GitHubActivityReporter.Bootstrap.Templates;

/// <summary>Scriban template of the generated GitHub Actions workflow.</summary>
public static class WorkflowTemplate
{
    public const string FileName = "update-activity-report.yml";

    public const string RelativeDirectory = ".github/workflows";

    public const string Scriban =
        """
        # This file is generated by github-activity-reporter.
        # Re-run `github-activity-reporter install-workflow` after changing the schedule.
        name: {{ workflow_name }}

        on:
          workflow_dispatch:
        {{- if cron }}
          schedule:
            # {{ schedule_description }}
            - cron: "{{ cron }}"
        {{- end }}

        permissions:
          contents: read
        {{- if github_pages_enabled }}
          pages: write
          id-token: write
        {{- end }}
        {{- if ai_summary_enabled && ai_provider == "github-models" }}
          models: read
        {{- end }}

        concurrency:
          group: activity-report
          cancel-in-progress: false

        jobs:
          update-activity-report:
            runs-on: ubuntu-latest
        {{- if github_pages_enabled }}
            environment:
              name: github-pages
              url: ${{ '{{' }} steps.deployment.outputs.page_url {{ '}}' }}
        {{- end }}

            steps:
              - name: Checkout reporter source
                uses: actions/checkout@v5
                with:
                  fetch-depth: 0

              - name: Checkout profile repository
                uses: actions/checkout@v5
                with:
                  repository: {{ profile_repository }}
                  ref: {{ branch }}
                  path: {{ profile_repository_path }}
                  token: ${{ '{{' }} secrets.{{ token_secret_name }} {{ '}}' }}
                  fetch-depth: 0

              - name: Setup .NET
                uses: actions/setup-dotnet@v5
                with:
                  dotnet-version: "{{ dotnet_version }}"

              - name: Restore
                run: dotnet restore {{ solution_path }}

              - name: Build
                run: dotnet build {{ solution_path }} --configuration Release --no-restore

              - name: Test
                run: dotnet test {{ solution_path }} --configuration Release --no-build

              - name: Configure profile repository Git identity
                run: |
                  git -C {{ profile_repository_path }} config user.name "github-actions[bot]"
                  git -C {{ profile_repository_path }} config user.email "41898282+github-actions[bot]@users.noreply.github.com"

              - name: Generate and publish activity report
                env:
                  {{ token_secret_name }}: ${{ '{{' }} secrets.{{ token_secret_name }} {{ '}}' }}
        {{- if email_enabled }}
                  {{ email_secret_name }}: ${{ '{{' }} secrets.{{ email_secret_name }} {{ '}}' }}
        {{- end }}
        {{- if slack_enabled }}
                  {{ slack_secret_name }}: ${{ '{{' }} secrets.{{ slack_secret_name }} {{ '}}' }}
        {{- end }}
        {{- if ai_summary_enabled }}
        {{- if ai_uses_github_token }}
                  {{ ai_secret_name }}: ${{ '{{' }} github.token {{ '}}' }}
        {{- else }}
                  {{ ai_secret_name }}: ${{ '{{' }} secrets.{{ ai_secret_name }} {{ '}}' }}
        {{- end }}
        {{- end }}
                run: dotnet run --project {{ cli_project_path }} --configuration Release --no-build -- run --config {{ config_path }} --profile-path {{ profile_repository_path }} --verbose

              - name: Validate generated output
                run: dotnet run --project {{ cli_project_path }} --configuration Release --no-build -- validate --config {{ config_path }} --path {{ profile_repository_path }}/generated

              - name: Detect profile changes
                id: profile_changes
                run: |
                  if [ -n "$(git -C {{ profile_repository_path }} status --porcelain)" ]; then
                    echo "changed=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "changed=false" >> "$GITHUB_OUTPUT"
                  fi

              - name: Commit and push profile changes
                if: steps.profile_changes.outputs.changed == 'true'
                run: |
                  git -C {{ profile_repository_path }} add -A
                  git -C {{ profile_repository_path }} commit -m "{{ commit_message }}"
                  git -C {{ profile_repository_path }} push origin HEAD:{{ branch }}
        {{- if github_pages_enabled }}

              - name: Upload GitHub Pages artifact
                uses: actions/upload-pages-artifact@v4
                with:
                  path: {{ github_pages_output_directory }}

              - name: Deploy GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
        {{- end }}
        """;
}
